#!/bin/bash
#######################################
## docker-rutorrent                  ##
## A full rutorrent setup for docker ##
#######################################
## rtorrent startup script           ##
#######################################

## Setup defaults if not existing
if [ ! -f /home/rtorrent/.rtorrent.rc ]; then
  cp /docker/rtorrent/rtorrentrc /home/rtorrent/.rtorrent.rc
  chown rtorrent:rtorrent /home/rtorrent/.rtorrent.rc
fi

mkdir -p /home/rtorrent/.rtorrent/session
mkdir -p /home/rtorrent/Downloads
mkdir -p /home/rtorrent/Torrents
# Clean up rtorrent sessions
rm /home/rtorrent/.rtorrent/session/.lock

# Make sure permissions are correct
chown -R rtorrent: /home/rtorrent

# Start rtorrent
exec /sbin/setuser rtorrent rtorrent
